### PR TITLE
Deprecate internal code loading; add runtime inclusion option.

### PR DESCRIPTION
**Pull request by willow-ahrens**
This change would deprecate the custom code loading in MatrixDepot. In particular, this makes three key changes:

1. MatrixDepot will no longer create or write to `MYDEPOT`. While MatrixDepot still reads these files, it will issue a deprecation warning if they are not the default files.
2. MatrixDepot no longer serializes user-defined generators because they may or may not be loaded when the database is deserialized
3. The Documentation now explains the replacement functionality, which directs users to call include_generator from outside of MatrixDepot at runtime, then reinitialize.

### CODE REVIEW

**Comment by willow-ahrens** [comment]
Note that we cannot remove the code associated with determining the path of `MYDEPOT` until we move from deprecation to removal at some point in the future.

**Comment by KlausC** [comment]
This PR is targeting only your clone of https://github.com/JuliaMatrices/MatrixDepot.jl, what explains, that we did not receive notifications.

**Comment by willow-ahrens** [comment]
That's correct, this is a PR on a PR (https://github.com/JuliaMatrices/MatrixDepot.jl/pull/75). If you'd prefer, I can retarget this as a PR directly to MatrixDepot after https://github.com/JuliaMatrices/MatrixDepot.jl/pull/75 is merged.

**Comment by willow-ahrens** [comment]
These changes have been moved to https://github.com/JuliaMatrices/MatrixDepot.jl/pull/79

**Pull request closed without merging**
